[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# don't build PyPy wheels, install from source instead
skip = "pp*"
