from typing import Dict, Union, List

SchemaType = Union[str, List, Dict]

def load_schema(schema_path: str) -> Dict: ...
def parse_schema(
    schema: SchemaType, expand: bool, _write_hint: bool, _force: bool
) -> SchemaType: ...
def fullname(schema: Dict) -> str: ...
def expand_schema(schema: Dict) -> Dict: ...
def to_canonical_form(schema: SchemaType) -> str: ...
