name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"


jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
        py:
          - 3.9
          - 3.8
          - 3.7
          - 3.6
          - pypy3
    steps:
      - name: Setup Python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Install Snappy
        run: |
          sudo apt-get install -y libsnappy-dev
          pip install python-snappy
      - uses: actions/checkout@v2
      - name: Install Testing Dependencies
        run: pip install -r developer_requirements.txt
      - name: Run Tests
        run: |
          ./run-tests.sh
          codecov
