name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"


jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py:
          - 3.9
          - 3.8
          - 3.7
          - 3.6
          - pypy3
    steps:
      - name: Setup Python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Install OS dependencies
        run: |
          for i in 1 2 3; do
            echo "try $i" && \
            ${{ runner.os == 'Linux' && 'sudo apt-get install -y libsnappy-dev && pip install python-snappy' || true}} && \
            ${{ runner.os == 'macOS' && 'brew update -vvv && brew install snappy && CPPFLAGS="-I/usr/local/include -L/usr/local/lib" python -m pip install python-snappy' || true}} && \
            exit 0 || true;
          done
          exit 1
        shell: bash
      - uses: actions/checkout@v2
      - name: Install Testing Dependencies
        run: pip install -r developer_requirements.txt
      - name: Run Tests
        run: |
          ./run-tests.sh
          codecov
